version: '3.8'

services:
  web:
    build:
      context: .
    container_name: parkcontrol_web
    command: gunicorn parkcontrol.wsgi:application --chdir parkcontrol --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - parkcontrol

  nginx:
    image: nginx:1.24
    container_name: nginx_https
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - parkcontrol

networks:
  parkcontrol:
    driver: bridge
